package fb.corba;

/**
* fb/corba/FlightBookingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fb.idl
* Monday, April 28, 2014 7:42:10 PM CST
*/

public final class FlightBookingHolder implements org.omg.CORBA.portable.Streamable
{
  public fb.corba.FlightBooking value = null;

  public FlightBookingHolder ()
  {
  }

  public FlightBookingHolder (fb.corba.FlightBooking initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = fb.corba.FlightBookingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    fb.corba.FlightBookingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return fb.corba.FlightBookingHelper.type ();
  }

}
