package fb.corba;


/**
* fb/corba/FlightBookingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fb.idl
* Monday, April 28, 2014 7:42:10 PM CST
*/

public interface FlightBookingOperations 
{
  String[] cities ();
  String[] flights (String fromCity, String toCity, String departTime);

  //query the specific flight lists
  boolean register (String name, String phone, String mail, String creditcard);
  boolean book (String fid, String username);
} // interface FlightBookingOperations
