package fb.corba;


/**
* fb/corba/_FlightBookingStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fb.idl
* Monday, April 28, 2014 7:42:10 PM CST
*/

public class _FlightBookingStub extends org.omg.CORBA.portable.ObjectImpl implements fb.corba.FlightBooking
{

  public String[] cities ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cities", true);
                $in = _invoke ($out);
                String $result[] = fb.corba.cityListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cities (        );
            } finally {
                _releaseReply ($in);
            }
  } // cities

  public String[] flights (String fromCity, String toCity, String departTime)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("flights", true);
                $out.write_string (fromCity);
                $out.write_string (toCity);
                $out.write_string (departTime);
                $in = _invoke ($out);
                String $result[] = fb.corba.airlineListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return flights (fromCity, toCity, departTime        );
            } finally {
                _releaseReply ($in);
            }
  } // flights


  //query the specific flight lists
  public boolean register (String name, String phone, String mail, String creditcard)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("register", true);
                $out.write_string (name);
                $out.write_string (phone);
                $out.write_string (mail);
                $out.write_string (creditcard);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return register (name, phone, mail, creditcard        );
            } finally {
                _releaseReply ($in);
            }
  } // register

  public boolean book (String fid, String username)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("book", true);
                $out.write_string (fid);
                $out.write_string (username);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return book (fid, username        );
            } finally {
                _releaseReply ($in);
            }
  } // book

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:fb/corba/FlightBooking:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _FlightBookingStub
