package fb.corba;


/**
* fb/corba/FlightBookingPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fb.idl
* Monday, April 28, 2014 7:42:10 PM CST
*/

public abstract class FlightBookingPOA extends org.omg.PortableServer.Servant
 implements fb.corba.FlightBookingOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cities", new java.lang.Integer (0));
    _methods.put ("flights", new java.lang.Integer (1));
    _methods.put ("register", new java.lang.Integer (2));
    _methods.put ("book", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // fb/corba/FlightBooking/cities
       {
         String $result[] = null;
         $result = this.cities ();
         out = $rh.createReply();
         fb.corba.cityListHelper.write (out, $result);
         break;
       }

       case 1:  // fb/corba/FlightBooking/flights
       {
         String fromCity = in.read_string ();
         String toCity = in.read_string ();
         String departTime = in.read_string ();
         String $result[] = null;
         $result = this.flights (fromCity, toCity, departTime);
         out = $rh.createReply();
         fb.corba.airlineListHelper.write (out, $result);
         break;
       }


  //query the specific flight lists
       case 2:  // fb/corba/FlightBooking/register
       {
         String name = in.read_string ();
         String phone = in.read_string ();
         String mail = in.read_string ();
         String creditcard = in.read_string ();
         boolean $result = false;
         $result = this.register (name, phone, mail, creditcard);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // fb/corba/FlightBooking/book
       {
         String fid = in.read_string ();
         String username = in.read_string ();
         boolean $result = false;
         $result = this.book (fid, username);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:fb/corba/FlightBooking:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FlightBooking _this() 
  {
    return FlightBookingHelper.narrow(
    super._this_object());
  }

  public FlightBooking _this(org.omg.CORBA.ORB orb) 
  {
    return FlightBookingHelper.narrow(
    super._this_object(orb));
  }


} // class FlightBookingPOA
