package fb.corba;


/**
* fb/corba/FlightBookingHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from fb.idl
* Monday, April 28, 2014 7:42:10 PM CST
*/

abstract public class FlightBookingHelper
{
  private static String  _id = "IDL:fb/corba/FlightBooking:1.0";

  public static void insert (org.omg.CORBA.Any a, fb.corba.FlightBooking that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static fb.corba.FlightBooking extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (fb.corba.FlightBookingHelper.id (), "FlightBooking");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static fb.corba.FlightBooking read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FlightBookingStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, fb.corba.FlightBooking value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static fb.corba.FlightBooking narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof fb.corba.FlightBooking)
      return (fb.corba.FlightBooking)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      fb.corba._FlightBookingStub stub = new fb.corba._FlightBookingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static fb.corba.FlightBooking unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof fb.corba.FlightBooking)
      return (fb.corba.FlightBooking)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      fb.corba._FlightBookingStub stub = new fb.corba._FlightBookingStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
